# Generated by Django 4.1.4 on 2022-12-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='marca',
            new_name='marca_auto',
        ),
    ]
